import type { NextPage } from "next";
import Head from "next/head";
const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>index</title>
        <meta name="description" content="Generated by pablovass" />
        <link rel="stylesheet" href="/favicon.ico" />
      </Head>
      <main >
<h1>hola mundo</h1>
      </main>
      <footer></footer>
    </div>

  );
}
export default Home
