import Image from "next/image";

export default function Home() {
  return (
   <div>
    <head>
      <title>prototype</title>
      <meta name="description" content="Generated by Pablovass"/>
      <link rel="stylesheet" href="/favicon.ico" />
      <link href="./output.css" rel="stylesheet"></link>
    </head>
    <main>
    <h1 class="text-3xl font-bold underline">
    Hello world!
  </h1>
    </main>
    <footer></footer>
   </div>
  );
}
